type Skill = {
  name: string;
  src: string;

}

export const skills: Skill[] = [
  { name: "TypeScript",
    src: "/assets/skills/typescript-logo-centered.png",  
  },
  { name: "JavaScript",
    src: "/assets/skills/jslogo-rounded.png",
  },
  { name: "HTML5",
    src: "/assets/skills/html5logo.png",
  },
  { name: "CSS3",
    src: "/assets/skills/css3logo.png",
  },
  { name: "React.js",
    src: "/assets/skills/react-1-logo.png",
  },
  { name: "ReactNative",
    src: "/assets/skills/react-native-logo-png.jpeg",
  },
  { name: "Styled-Components",
    src: "/assets/skills/styled-components-2.png",
  },
  { name: "Tailwind",
    src: "/assets/skills/tailwind-logo.jpg",
  },
  { name: "Node.js",
    src: "/assets/skills/nodejs.svg",
  },
  { name: "Express",
    src: "/assets/skills/expressjs-logo.svg",
  },
  { name: "MongoDB",
    src: "/assets/skills/mongodb-logo.png",
  },
  { name: "GraphQL",
    src: "/assets/skills/GraphQL_Logo.png",
  },
  { name: "REST",
    src: "/assets/skills/REST-2-logo.png",
  },
  { name: "Vite",
    src: "/assets/skills/vite-logo.png",
  },
  { name: "Next",
    src: "/assets/skills/next-logo.jpg",
  },
]