type Skill = {
  name: string;
  src: string;

}

export const skills: Skill[] = [
  { name: "TypeScript",
    src: "/assets/skills/TSlogo.svg",  
  },
  { name: "JavaScript",
    src: "/assets/skills/jslogo.png",
  },
  { name: "HTML5",
    src: "/assets/skills/HTML5_Logo.png",
  },
  { name: "CSS3",
    src: "/assets/skills/css3-logo.png",
  },
  { name: "React.js",
    src: "/assets/skills/react-1-logo.png",
  },
  { name: "ReactNative",
    src: "/assets/skills/react-native-logo-png.jpeg",
  },
  { name: "Styled-Components",
    src: "/assets/skills/styled-components-logo.png",
  },
  { name: "Tailwind",
    src: "/assets/skills/tailwind-logo.jpg",
  },
  { name: "Node.js",
    src: "/assets/skills/node-logo.png",
  },
  { name: "Express",
    src: "/assets/skills/express-logo.png",
  },
  { name: "MongoDB",
    src: "/assets/skills/mongodb-logo.png",
  },
  { name: "GraphQL",
    src: "/assets/skills/GraphQL_Logo.png",
  },
  { name: "REST",
    src: "/assets/skills/REST-2-logo.webp",
  },
  { name: "Vite",
    src: "/assets/skills/vite-logo.png",
  },
  { name: "Next",
    src: "/assets/skills/next-logojpg",
  },
]