import Head from 'next/head';
import Header from '@/components/Header';
import Hero from '@/components/Hero';
import About from '@/components/About';
import WorkExperience from '@/components/WorkExperience';
import Skills from '@/components/Skills';
import Projects from '@/components/Projects';
import Contact from '@/components/Contact';
import Footer from '@/components/Footer';
import Link from 'next/link';


// Things to implent:
// next images fix
// snackbar for the form
// fix text and buttons accessibility
// change project design with CSS variables
// projects pages
// darkmode
// add generative arts and the rotating and gradient square/circle animation
// change hero animation for the tunel effect


export default function Home() {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#f7ac0a]/80 scrollbar-rounded-full z-0'>
      <Head>
        <title>Carlos Cravo Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

    <Header />

    <section id="hero" className='snap-start'>
      <Hero />
    </section>

    <section id="about" className='snap-start'>
      <About />
    </section>
    
    <section id="skills" className='snap-start'>
      <Skills />
    </section>

    <section id="projects" className='snap-center'>
      <Projects />
    </section>

    <section id="experience" className='snap-center'>
      <WorkExperience />
    </section>

    <section id="contact" className='snap-start'>
      <Contact />
    </section>

    
    <Footer />
    
    </div>
  )
}
